### ISSUE TITLE
Preact support on npm

### ISSUE THREAD

**Issue by ruhusobeje** [cristianbote/react-translate-json#4]
Thanks for the super small library!
We are using preact.
I see preact implementation here on Github but not when I install from npm
Can you please publish latest code to npm registry?

**Comment by cristianbote** [comment]
Hey @ruhusobeje, thanks for reporting it!

Indeed it seems that when I introduced the support for `preact` I forgot to update the `package.files` entries. Should be working now.

Let me know if there's anything else.
