### ISSUE TITLE
weird behavior with Redux?

### ISSUE THREAD

**Issue by Karyum** [cristianbote/react-translate-json#5]
hey thanks for the package!
I just wanted to report something small ( _but the problem might have been from me :grimacing:_ ), I could only get this package working when i remove [children[0] from index.js from the TranslateProvider here](https://github.com/cristianbote/react-translate-json/blob/master/index.js#L217).

I was wrapping the `TranslateProvider`  around my `ReduxProvider` and it would not render anything and the function `TranslateProvider`  was returning `undefined`, any idea why ?

```html
return (
      <TranslateProvider
        locale={this.state.locale}
        fallbackLocale={"en"}
        pathPrefix={"/api/translations"}
      >
        <ReduxProvider store={store}>
          <ClientApp />
        </ReduxProvider>
      </TranslateProvider>
    )
```

this is what i was returning from my app's index.jsx file (`ClientApp` is my react router)

**Comment by cristianbote** [comment]
Hey @Karyum,

Thanks for reaching out!

This looks strange indeed. It seems that the new _fiber_ changed some things. Will do a fix for this, asap.

Thanks again!

**Comment by cristianbote** [comment]
Hey, I just pushed `2.1.0` should be fine now.

Test it on https://codesandbox.io/s/5v5v9o3zzx

**Comment by Karyum** [comment]
yup it worked
Thanks!
